version: "3.9"


services:

  postgres:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./postgres/init_tables.sql:/docker-entrypoint-initdb.d/1-init_tables.sql
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    command: -p $DB_PORT
    restart: always

  app:
    build:
      context: .
      target: main
    ports:
      - "$DOCKER_SERVER_PORT:$SERVER_PORT"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      SERVER_HOST: 0.0.0.0
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_volume:
