version: "3.9"


services:

  postgres:
    image: postgres
    volumes:
      - ./postgres/extensions.sql:/docker-entrypoint-initdb.d/1-extensions.sql
    environment:
      - POSTGRES_USER=$TEST_DB_USER
      - POSTGRES_PASSWORD=$TEST_DB_PASSWORD
      - POSTGRES_DB=$TEST_DB_NAME
    command: -p $TEST_DB_PORT

  app:
    build:
      context: .
      target: test
    env_file:
      - .env
    environment:
      TEST_DB_HOST: postgres
    depends_on:
      - postgres
