version: "3.9"


services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=my_vocab_db_user
      - POSTGRES_PASSWORD=my_vocab_db_password
      - POSTGRES_DB=test_my_vocab
    restart: on-failure

  pytest:
    build:
      context: .
      target: test
    env_file:
      - .env.test
    environment:
      APP_ENV: test
      DB_URI: postgresql://my_vocab_db_user:my_vocab_db_password@postgres:5432/test_my_vocab
    depends_on:
      - postgres

  lint:
    build:
      context: .
      target: test
    environment:
      MYPY_CACHE_DIR: /dev/null
    command: bash -c "
        flake8 app &&
        flake8 tests &&
        mypy app &&
        mypy tests --disable-error-code=override --disable-error-code=misc --disable-error-code=no-untyped-def
      "