version: "3.9"


services:

  redis:
    image: redis
    restart: always

  postgres:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=my_vocab_db_user
      - POSTGRES_PASSWORD=my_vocab_db_password
      - POSTGRES_DB=my_vocab
    restart: always

  migration:
    build:
      context: .
      target: main
    env_file:
      - .env.dev
    environment:
      APP_ENV: dev
      DB_URL: postgresql://my_vocab_db_user:my_vocab_db_password@postgres:5432/my_vocab
      REDIS_URL: redis://redis:6379/
    depends_on:
      - postgres
    command: alembic upgrade head
    restart: on-failure

  uvicorn:
    build:
      context: .
      target: main
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    environment:
      APP_ENV: dev
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      UVICORN_RELOAD: 0
      DB_URL: postgresql://my_vocab_db_user:my_vocab_db_password@postgres:5432/my_vocab
      REDIS_URL: redis://redis:6379/
    depends_on:
      - redis
      - migration
    restart: always

volumes:
  postgres_volume:
