version: "3.9"


services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=$TEST_DB_USER
      - POSTGRES_PASSWORD=$TEST_DB_PASSWORD
      - POSTGRES_DB=$TEST_DB_NAME
    command: -p $TEST_DB_PORT

  app:
    build:
      context: .
      target: test
    ports:
      - "8000:$SERVER_PORT"
    env_file:
      - .env
    environment:
      TEST_DB_HOST: postgres
      SERVER_HOST: 0.0.0.0
    depends_on:
      - postgres
