version: "3.9"


services:

  postgres:
    image: postgres
    networks:
      - backend_network
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=my_vocab_db_user
      - POSTGRES_PASSWORD=my_vocab_db_password
      - POSTGRES_DB=my_vocab
    restart: always

  migration:
    build:
      context: .
      target: main
    networks:
      - backend_network
    env_file:
      - .env.prod
    environment:
      APP_ENV: prod
      DB_URI: postgresql://my_vocab_db_user:my_vocab_db_password@postgres:5432/my_vocab
    depends_on:
      - postgres
    command: alembic upgrade head
    restart: on-failure

  gunicorn:
    build:
      context: .
      target: main
    networks:
      backend_network:
        aliases:
          - gunicorn_host
    expose:
      - 8000
    env_file:
      - .env.prod
    environment:
      APP_ENV: prod
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      DB_URI: postgresql://my_vocab_db_user:my_vocab_db_password@postgres:5432/my_vocab
    depends_on:
      - migration
    restart: always

  nginx:
    build:
      context: ./nginx
    networks:
      - backend_network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gunicorn
    restart: always


networks:
  backend_network: {}

volumes:
  postgres_volume: {}
