version: "3.9"


services:
  redis:
    image: redis
    restart: always

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: my_vocab_db_user
      POSTGRES_PASSWORD: my_vocab_db_password
      POSTGRES_DB: test_my_vocab
    restart: always

  test:
    build:
      context: .
      target: test
    env_file:
      - .env.test
    environment:
      MYPY_CACHE_DIR: /dev/null
      APP_ENV: test
      DB_URL: postgresql://my_vocab_db_user:my_vocab_db_password@postgres:5432/test_my_vocab
      REDIS_URL: redis://redis:6379/
    depends_on:
      - postgres
      - redis