version: 1
disable_existing_loggers: false
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

    detailed:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s - %(funcName)s() [%(lineno)s] : %(message)s"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


filters:
    # only DEBUG
    DEBUGFilter:
        (): app.utils.logging_.filters.LevelFilter
        level: DEBUG

    # only INFO
    INFOFilter:
        (): app.utils.logging_.filters.LevelFilter
        level: INFO
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


handlers:
    debug_console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: detailed
        stream: ext://sys.stdout
        filters: [DEBUGFilter]

    info_console:
        class: logging.StreamHandler
        level: INFO
        formatter: detailed
        stream: ext://sys.stdout
        filters: [INFOFilter]

    error_console:
        class: logging.StreamHandler
        level: WARN
        formatter: detailed
        stream: ext://sys.stderr
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


# root logger
root:
    level: INFO
    handlers: [debug_console, info_console, error_console]
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


# loggers
loggers:
    # sqlalchemy namespace
    sqlalchemy.engine:
        level: INFO
        propagate: True
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -