name: Testing / Type-checking / Linting

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: my_vocab_db_user
          POSTGRES_PASSWORD: my_vocab_db_password
          POSTGRES_DB: my_vocab
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip && \
          python -m pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --system --deploy --dev

      - name: Run flake8
        run: |
          flake8 app && \
          flake8 tests

      - name: Run mypy
        run: |
          mypy app && \
          mypy tests --disable-error-code=override --disable-error-code=misc --disable-error-code=no-untyped-def

      - name: Run tests
        run: |
          pytest
        env:
          APP_ENV: test
          DB_URI: postgresql://my_vocab_db_user:my_vocab_db_password@localhost:5432/my_vocab